In [1]:
import numpy as np
import pandas as pd

In [3]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2, 3],
              [4, 5, 6]])

a3 = np.array([[[1, 2, 3],
              [4, 5, 6]],
              [[7, 8, 9],
              [10, 11, 12]],
              [[13, 14, 15],
              [16, 17, 18]]])

In [4]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [7]:
# Create a DataFrame out of one of the arrays
a2_df = pd.DataFrame(a2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))

In [10]:
# Create an array within a range of 0 and 100 with step 3
ar100 = np.arange(0,100,3)
ar100

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[6, 4],
       [4, 9],
       [2, 0],
       [7, 2],
       [9, 5],
       [1, 0],
       [3, 0]])

In [23]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_float = np.random.random((3,5))
random_array_float

array([[0.21260635, 0.05971676, 0.26511064, 0.24888749, 0.48215672],
       [0.96625517, 0.36761421, 0.87720849, 0.91626662, 0.67053871],
       [0.3026208 , 0.53317171, 0.58461156, 0.66529456, 0.87767664]])

In [33]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_seeded = np.random.random((4,6))
random_seeded

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array1 = np.random.randint(10, size=(3,7))

# Find the unique numbers in the array you just created
random_array1, np.unique(random_array1)

(array([[6, 7, 2, 0, 3, 1, 7],
        [3, 1, 5, 5, 9, 3, 5],
        [1, 9, 1, 9, 3, 7, 6]]),
 array([0, 1, 2, 3, 5, 6, 7, 9]))

In [50]:
# Find the 0'th index of the latest array you created
random_array1[0]

array([6, 7, 2, 0, 3, 1, 7])

In [39]:
# Get the first 2 rows of latest array you created
random_array1[:2]

array([[6, 7, 2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9, 3, 5]])

In [66]:
# Get the first 2 values of the first 2 rows of the latest array
random_array1[:2, :2]

array([[6, 7],
       [3, 1]])

In [77]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ra = np.random.randint(10, size=(3,5))
ones = np.ones((3,5))

In [84]:
a1 + a2

array([[2, 4, 6],
       [5, 7, 9]])

In [85]:
a1 - a2

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [86]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [87]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [88]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [93]:
np.mean(a2), np.max(a2), np.min(a2)

(3.5, 6, 1)

In [94]:
np.std(a2)

1.707825127659933

In [95]:
np.var(a2)

2.9166666666666665

In [102]:
# Reshape the array to (3, 6, 1)
a3, a3.reshape(3, 6, 1)

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 array([[[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6]],
 
        [[ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12]],
 
        [[13],
         [14],
         [15],
         [16],
         [17],
         [18]]]))

In [103]:
# Transpose the latest array
a3, a3.T

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 array([[[ 1,  7, 13],
         [ 4, 10, 16]],
 
        [[ 2,  8, 14],
         [ 5, 11, 17]],
 
        [[ 3,  9, 15],
         [ 6, 12, 18]]]))

In [110]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar1 = np.random.randint(10, size = (4, 3))
ar2 = np.random.randint(10, size = (4, 3))
ar1,ar2

(array([[7, 8, 4],
        [0, 2, 9],
        [7, 5, 7],
        [8, 3, 0]]),
 array([[0, 9, 3],
        [6, 1, 2],
        [0, 4, 0],
        [7, 0, 0]]))

In [111]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(ar1,ar2.T)

array([[84, 58, 32, 49],
       [45, 20,  8,  0],
       [66, 61, 20, 49],
       [27, 51, 12, 56]])

In [113]:
# Compare the two arrays with '>'
ar1 > ar2

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [114]:
# Compare the two arrays with '>='
ar1 >= ar2

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [115]:
# Find which elements of the first array are greater than 7
ar1 > 7

array([[False,  True, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [116]:
# Which parts of each array are equal? (try using '==')
ar1 == ar2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [121]:
# Sort one of the arrays you just created in ascending order
ar1, np.sort(ar1)

(array([[7, 8, 4],
        [0, 2, 9],
        [7, 5, 7],
        [8, 3, 0]]),
 array([[4, 7, 8],
        [0, 2, 9],
        [5, 7, 7],
        [0, 3, 8]]))

In [120]:
# Sort the indexes of one of the arrays you just created
ar1, np.argsort(ar1)

(array([[7, 8, 4],
        [0, 2, 9],
        [7, 5, 7],
        [8, 3, 0]]),
 array([[2, 0, 1],
        [0, 1, 2],
        [1, 0, 2],
        [2, 1, 0]], dtype=int64))

In [122]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar1)

5

In [123]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar1)

3

In [124]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar1, axis = 1)

array([1, 2, 0, 0], dtype=int64)

In [125]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar1, axis = 0)

array([1, 1, 3], dtype=int64)

In [132]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.06437805,  0.34490234, -0.08008734, -0.24138013,  1.43351549],
       [ 1.06579371, -2.49875914,  1.48032856,  2.15872852,  1.23177838],
       [-0.21432448, -0.68919421,  0.72783311, -0.61906936,  0.35615983]])

In [130]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array_even = np.arange(1, 101, 1)
array_even

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [1]:
# turn an image into a NumPy array
from matplotlib.image import imread
panda = imread("images/numpy-panda.png")

In [2]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [3]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.